// SPDX-License-Identifier: CC-BY-NC-SA-4.0
import { parseTextCatalogSetV1 } from "@sillymaker/base";

import { pocTextIdsV1 } from "../../content/ids.js";

type PocTextNameV1 = keyof typeof pocTextIdsV1;

const pocZhCnTextByNameV1 = {
  storyTitle: "旅店的一周",
  settingsContentFilterNone: "当前故事没有可调整的内容过滤选项。",

  calendarDay1Label: "周一",
  calendarDay2Label: "周二",
  calendarDay3Label: "周三",
  calendarDay4Label: "周四",
  calendarDay5Label: "周五",
  calendarDay6Label: "周六",
  calendarDay7Label: "周日",
  calendarPhaseMorningLabel: "上午",
  calendarPhaseAfternoonLabel: "下午",
  calendarPhaseEveningLabel: "夜晚",

  hudActionPointsLabel: "行动点",
  hudPlayerStaminaLabel: "主角体力",
  hudHeroineStaminaLabel: "女主体力",
  hudCashLabel: "现金",
  hudReputationLabel: "人气",
  hudLevyLabel: "重建税",

  overlayPolicyTitle: "生活策略",
  overlayInventoryTitle: "库存",
  overlayPurchaseTitle: "采购食材",
  overlayTavernPlanTitle: "营业计划",
  overlayFacilityTitle: "设施建设",
  overlayWorldActionTitle: "旧贸易路线调查",
  overlayLedgerTitle: "经营账本",
  overlayRelationshipTitle: "人物关系",
  overlayRunSummaryTitle: "本周总结",

  controlCloseLabel: "关闭",
  controlCancelLabel: "取消",
  controlConfirmLabel: "确认",
  controlConfirmPurchaseLabel: "确认采购",
  controlConfirmTavernPlanLabel: "确认营业计划",
  controlConfirmFacilityLabel: "确认设施选择",
  controlConfirmWorldActionLabel: "确认出发",
  controlAddLineLabel: "添加一项",
  controlRemoveLineLabel: "移除",

  formIngredientLabel: "食材",
  formQuantityLabel: "数量",
  formRecipeLabel: "菜品",
  formPortionsLabel: "份数",
  formServiceModeLabel: "营业方式",

  sectionInventoryTableLabel: "完整库存",
  sectionInventoryEmptyLabel: "暂无库存",
  sectionLedgerEmptyLabel: "暂无账目",
  sectionStartingCashLabel: "初始现金",
  sectionCurrentCashLabel: "当前现金",
  sectionLedgerAmountLabel: "金额",
  sectionLedgerReasonLabel: "原因",
  sectionAffectionLabel: "好感",
  sectionTeamworkLabel: "默契",
  sectionMoodLabel: "心情",
  sectionEndingLabel: "本周结局",
  sectionPreviewLabel: "行动预览",

  rejectionRunInvalidStatus: "当前游戏状态不允许这个行动",
  rejectionRunAlreadyStarted: "本周已经开始",
  rejectionRunNotStarted: "本周尚未开始",
  rejectionRunPolicyRequired: "请先选择生活策略",
  rejectionCommandUnknownReference: "行动引用了不存在的内容",
  rejectionCommandBlockedByNarrative: "当前剧情需要先处理",
  rejectionCommandBlockedByWorkflow: "当前流程需要先完成",
  rejectionPolicyAlreadyChosen: "生活策略已经选择",
  rejectionCalendarInvalidPhase: "当前时段不允许这个行动",
  rejectionCalendarInsufficientAp: "行动点不足",
  rejectionCalendarPhaseBlocked: "当前时段仍有待处理事项",
  rejectionActionUnavailable: "这个行动当前不可用",
  rejectionActorInsufficientStamina: "体力不足",
  rejectionActorStaminaAtMaximum: "体力已经恢复到上限",
  rejectionTavernPreparationLimitReached: "今日准备已达到上限",
  rejectionInventoryInvalidQuantity: "采购数量无效",
  rejectionInventoryDuplicateLine: "同一种食材不能重复添加",
  rejectionInventoryLineLimitExceeded: "采购项目超过上限",
  rejectionInventoryInsufficientCash: "现金不足",
  rejectionInventoryInsufficientIngredient: "食材库存不足",
  rejectionFacilityUnavailable: "当前设施机会不可用",
  rejectionFacilityTargetNotOffered: "这个设施不在本次候选中",
  rejectionFacilityAlreadyBuilt: "这个设施已经建成",
  rejectionFacilityChoiceCommitted: "本次设施选择已经确认",
  rejectionAuraAlreadyPresent: "这个状态已经存在",
  rejectionAuraNotFound: "找不到要移除的状态",
  rejectionTavernInvalidPlan: "营业计划无效",
  rejectionTavernPlanFrozen: "营业计划已经锁定",
  rejectionTavernServiceUnavailable: "这种营业方式当前不可用",
  rejectionTavernOpeningPlanMissing: "尚未制定营业计划",
  rejectionTavernEveningResolved: "今日营业已经结算",
  rejectionTavernOpeningActive: "营业准备正在进行",
  rejectionTavernOpeningMissing: "没有正在进行的营业准备",
  rejectionTavernOpeningCheckpointBlocked: "请先完成当前营业准备步骤",
  rejectionTavernOpeningContinueNotNeeded: "当前无需继续营业准备",
  rejectionTavernOpeningNotReady: "营业准备尚未完成",
  rejectionWorkflowConflict: "另一个流程正在进行",
  rejectionWorkflowMissing: "找不到正在进行的流程",
  rejectionWorldActionUnavailable: "旧贸易路线当前不可调查",
  rejectionWorldActionWrongPhase: "只能在指定时段执行外出行动",
  rejectionNarrativeInactive: "当前没有进行中的剧情",
  rejectionNarrativeCursorMismatch: "剧情进度已经变化",
  rejectionNarrativeChoiceRequired: "请先作出剧情选择",
  rejectionNarrativeChoiceHidden: "这个剧情选项当前不可见",
  rejectionNarrativeChoiceDisabled: "这个剧情选项当前不可选",
  rejectionLevyNotDue: "当前无需缴纳税款",
  rejectionStoryRuleRejected: "故事规则拒绝了这个行动",
  rejectionEngineInvariantRejected: "引擎一致性检查拒绝了这个行动",

  characterNarratorName: "旁白",
  characterPlayerName: "店主",
  characterHeroineName: "女主",

  reasonActionPurchase: "采购原料",
  reasonActionPrepareFood: "准备食物",
  reasonActionRest: "安排休息",
  reasonActionFacilityBuild: "建造设施",
  reasonActionFacilitySkip: "放弃本次设施机会",
  reasonRecoveryBalancedNight: "均衡作息带来的夜间恢复",
  reasonRecoveryNightOwlNight: "夜猫子作息带来的夜间恢复",
  reasonRecoveryHeroineNight: "女主角的夜间恢复",
  reasonServiceManual: "亲自负责营业",
  reasonServiceAssisted: "与女主角协作营业",
  reasonServiceDelegated: "委托帮手负责营业",
  reasonServiceClosed: "今日歇业",
  reasonServiceEmergencyClosed: "因准备不足而紧急歇业",
  reasonLedgerPurchase: "采购支出",
  reasonLedgerWage: "帮手工资",
  reasonLedgerOpeningFee: "营业成本",
  reasonLedgerRevenue: "营业收入",
  reasonLedgerDiscardedFood: "丢弃剩余食物",
  reasonLedgerSpoiledIngredient: "原料腐坏损失",
  reasonLedgerFacilityBuild: "设施建造支出",
  reasonLedgerWorldActionCost: "外出行动支出",
  reasonLedgerLevy: "缴纳税款",
  reasonModifierColdStorageShelfLife: "冷藏库延长了原料保鲜期",
  reasonModifierComfortableBedPlayerRecovery: "舒适床铺提高了店主恢复",
  reasonModifierComfortableBedHeroineRecovery: "舒适床铺提高了女主角恢复",
  reasonModifierReputationDemand: "口碑影响了顾客需求",
  reasonModifierWarClueDemand: "战争线索影响了旅客需求",
  reasonAuraSignRepaired: "修好的招牌正在吸引顾客",
  reasonAuraHeroineAngry: "女主角仍在生气",
  reasonAuraAdventureStrain: "外出冒险留下了疲劳",
  reasonEventTutorialCompleted: "首次营业教学已经完成",
  reasonEventInvoiceChecked: "供应商账单已经核查",
  reasonEventHelperUnlocked: "帮手已经可以协助营业",
  reasonObligationLevyForecast: "预计税款义务",
  reasonRelationshipRepairSign: "与女主角一起修理招牌",
  reasonRelationshipRepairSignDeclined: "婉拒了共同修理招牌",
  reasonRelationshipRepairSignConflict: "修理招牌时发生了争执",
  reasonRelationshipApology: "向女主角认真道歉",
  reasonInvestigationBegin: "开始调查旧贸易路线",
  reasonInvestigationSetback: "调查遭遇挫折",
  reasonInvestigationSuccessWithCost: "付出代价后取得调查进展",
  reasonInvestigationComplete: "完成旧贸易路线调查",
  reasonInvestigationExceptional: "调查取得了出色成果",
  reasonEndingStable: "旅店平稳度过了这一周",
  reasonEndingDanger: "旅店仍面临经营危机",
  reasonEndingArrears: "未能按时履行税款义务",
  reasonEndingReputationCrisis: "旅店口碑陷入危机",
  reasonUnavailableStoryWindowClosed: "这个故事机会已经错过",
  reasonUnavailableRelationshipResolved: "这段关系事件已经解决",
  reasonUnavailableInvestigationResolved: "调查已经结束",
  reasonUnavailableMutuallyExclusive: "已经选择了互斥的行动",
  reasonUnavailableHeroineNotAngry: "女主角目前并没有生气",
  reasonUnavailableFacilityDecided: "设施机会已经处理",
  reasonUnavailableTaxNotVisible: "税款义务尚未公开",
  reasonUnavailablePolicyNotReady: "目前还不能选择生活策略",
  reasonUnavailableServiceModeLocked: "这种营业方式尚未解锁",
  reasonUnavailableHelperLocked: "帮手尚未解锁",
  reasonUnavailableIntellectBRequired: "需要达到智力 B",
  reasonDebugStateOverride: "调试：覆盖游戏状态",
  reasonDebugCashAdjustment: "调试：调整现金",
  reasonDebugAuraAdjustment: "调试：调整 Aura",
  reasonDebugNarrativeJump: "调试：跳转叙事节点",
  reasonDebugRngOverride: "调试：覆盖随机数",

  segmentLocalsName: "本地居民",
  segmentTravelersName: "往来旅客",
  modifierSourceReputationName: "旅店口碑",
  modifierSourceWarClueName: "战争线索",

  actionChooseLifePolicyLabel: "选择生活策略",
  actionPurchaseLabel: "采购原料",
  actionPrepareFoodLabel: "准备食物",
  actionRestLabel: "休息",
  actionServicePlanLabel: "制定营业计划",
  actionAdvancePhaseLabel: "进入下一时段",
  actionPayLevyLabel: "缴纳税款",
  actionFacilityWindowLabel: "处理设施机会",
  actionRepairSignWithHeroineLabel: "和女主角一起修招牌",
  actionOldTradeRoadLabel: "调查旧贸易路线",
  actionApologizeToHeroineLabel: "向女主角道歉",
  actionRunStartLabel: "开始这一周",
  actionTavernOpeningStartLabel: "开始营业准备",
  actionTavernOpeningContinueLabel: "继续营业准备",
  actionTavernOpeningFinalizeLabel: "确认开门营业",
  actionWorldActionCompleteLabel: "完成外出行动",
  actionNarrativeAdvanceLabel: "继续",
  actionNarrativeChooseLabel: "选择",

  ingredientCoarseGrainName: "粗粮",
  ingredientRootVegetableName: "根茎蔬菜",
  ingredientAleName: "麦芽酒",
  ingredientFreshMeatName: "鲜肉",
  ingredientHerbName: "香草",
  recipeGrainRootPorridgeName: "粗粮根菜粥",
  recipeAleBreadName: "麦酒面包",
  recipeHunterStewName: "猎人炖肉",
  recipeTravelerRoastName: "旅人烤肉",
  policyBalancedName: "均衡作息",
  policyNightOwlName: "夜猫子作息",
  serviceModeManualName: "亲自营业",
  serviceModeAssistedName: "协作营业",
  serviceModeDelegatedName: "委托营业",
  serviceModeClosedName: "歇业",
  facilityColdStorageName: "冷藏库",
  facilityComfortableBedName: "舒适床铺",
  auraHeroineAngryName: "女主角生气",
  auraTavernSignRepairedName: "招牌焕新",
  auraPlayerAdventureStrainName: "冒险疲劳",

  choiceSupplierInvoiceIntellectBLabel: "仔细核查账单",
  choiceSupplierInvoicePayNormallyLabel: "按账单正常付款",
  choiceRepairSignCooperateLabel: "一起把招牌修好",
  choiceRepairSignDeclineLabel: "婉拒她的提议",
  choiceRepairSignConflictLabel: "坚持自己的做法",
  choiceOldTradeRoadBasicLabel: "基础准备",
  choiceOldTradeRoadPreparedLabel: "充分准备",
  choiceFacilitySkipLabel: "暂不建造设施",

  endingStableName: "平稳的一周",
  endingDangerName: "风雨欲来",
  endingFailedArrearsName: "税款逾期",
  obligationRecommendationPersonalService: "亲自参与营业，减少额外成本。",
  obligationRecommendationCheapMenu: "优先准备成本较低的菜单。",
  obligationRecommendationAvoidOverbuying: "避免采购超过本周所需的原料。",
  obligationRecommendationCommittedPlanReview: "复核已经确认的营业计划。",
  obligationRecommendationReplayLedger: "回看账本，找出资金变化的原因。",

  narrativeManifestStartCard: "一封旧信和一间待整顿的旅店，拉开了这一周的序幕。",
  narrativeFacilityWindowNotice: "你现在可以选择一项设施改善旅店。",
  narrativeLevyDueNotice: "本周税款已经到期。",
  narrativeRepairSignIntro: "女主角抱着木板站在旧招牌旁，等你决定要不要一起动手。",
  narrativeApologyLine: "你认真说完道歉的话，她沉默片刻，终于看向了你。",
  narrativeOldTradeRoadDepartureLine: "你离开小镇，沿着荒废的旧贸易路线前行。",
  narrativeOldTradeRoadInvestigationLine: "残留的车辙和路标，似乎指向一段被遗忘的往事。",

  stageSceneMainMenuAccessibleName: "主菜单",
  stageSceneTavernAccessibleName: "旅店主厅",
  stageSceneMarketAccessibleName: "小镇市集",
  stageSceneWorldMapAccessibleName: "小镇与周边地图",
  stageSceneWeekSummaryAccessibleName: "本周总结",
  stageVariantMainMenuDefaultAccessibleName: "旅店主菜单",
  stageVariantTavernDayAccessibleName: "酒馆主厅",
  stageVariantTavernEveningAccessibleName: "酒馆主厅",
  stageVariantMarketDayAccessibleName: "市集",
  stageVariantWorldMapDefaultAccessibleName: "小镇与旧贸易路线地图",
  stageVariantWeekSummaryDefaultAccessibleName: "七日经营总结",
  surfaceHeroineAccessibleName: "女主角互动区",
  surfaceTavernAccessibleName: "旅店互动区",
  surfaceMarketAccessibleName: "市集互动区",
  surfaceWorldMapAccessibleName: "世界地图互动区",
  targetHeroineFigureAccessibleName: "与女主互动",
  targetTavernServiceAccessibleName: "安排营业",
  targetMarketPurchaseAccessibleName: "采购",
  targetWorldMapOldTradeRoadAccessibleName: "旧贸易路线",
  behaviorHeroineOpenProfileName: "查看人物资料",
  behaviorHeroineOpenProfileDescription: "查看女主角的资料与当前关系。",
  behaviorHeroineRepairSignName: "一起修理招牌",
  behaviorHeroineRepairSignDescription: "回应女主角关于旧招牌的提议。",
  behaviorHeroineApologizeName: "认真道歉",
  behaviorHeroineApologizeDescription: "在合适的时机向女主角道歉。",
  behaviorTavernServicePlanName: "制定营业计划",
  behaviorTavernServicePlanDescription: "安排本次营业的菜单、份数和协作方式。",
  behaviorMarketPurchaseName: "采购原料",
  behaviorMarketPurchaseDescription: "在市集选择本周经营所需的原料。",
  behaviorWorldMapOldTradeRoadName: "前往旧贸易路线",
  behaviorWorldMapOldTradeRoadDescription: "选择准备方式并调查旧贸易路线。",

  confirmationBenefitPurchaseStock: "补充可用于备餐的原料库存。",
  confirmationRiskPurchaseCash: "采购会立即消耗现金。",
  confirmationBenefitPrepareFood: "把原料制作成可以营业出售的食物。",
  confirmationRiskPrepareFoodStamina: "备餐会消耗店主的体力。",
  confirmationBenefitRestRecovery: "休息可以恢复店主体力。",
  confirmationRiskRestTime: "休息会占用当前时段。",
  confirmationBenefitServiceManualControl: "亲自营业可以掌握全部服务细节。",
  confirmationRiskServiceManualStamina: "亲自营业会消耗较多体力。",
  confirmationBenefitServiceAssistedCapacity: "协作营业可以提高接待能力。",
  confirmationRiskServiceAssistedCost: "协作营业仍需要店主投入体力。",
  confirmationBenefitServiceDelegatedRecovery: "委托营业可以让店主休整。",
  confirmationRiskServiceDelegatedWage: "委托营业需要支付帮手工资。",
  confirmationBenefitServiceClosedRecovery: "歇业可以让大家充分恢复。",
  confirmationRiskServiceClosedIncome: "歇业不会产生营业收入。",
  confirmationBenefitColdStorageShelfLife: "冷藏库会延长易腐原料的保鲜期。",
  confirmationRiskColdStorageCost: "建造冷藏库需要一笔现金。",
  confirmationBenefitComfortableBedRecovery: "舒适床铺会提高每晚恢复。",
  confirmationRiskComfortableBedCost: "添置舒适床铺需要一笔现金。",
  confirmationBenefitFacilityBuildPermanent: "设施建成后会持续发挥作用。",
  confirmationRiskFacilityExclusiveChoice: "本周只能选择这一项设施。",
  confirmationBenefitFacilitySkipCash: "跳过建造可以保留当前现金。",
  confirmationRiskFacilitySkipOpportunity: "跳过后将失去本周的设施机会。",
  confirmationBenefitRepairSignRelationship: "共同劳动有助于改善彼此的默契。",
  confirmationRiskRepairSignConflict: "处理不当可能让争执升级。",
  confirmationBenefitApologyReconcile: "真诚道歉可能修复紧张关系。",
  confirmationRiskApologyWindow: "只有在合适的故事窗口内才能道歉。",
  confirmationBenefitOldTradeRoadClue: "调查可能带回影响旅店经营的线索。",
  confirmationRiskOldTradeRoadCost: "外出会消耗现金和体力。",
  confirmationBenefitOldTradeRoadPrepared: "充分准备可以提高调查结果。",
  confirmationRiskOldTradeRoadPreparedCost: "额外准备需要更多现金和体力。",
  confirmationBenefitInvoiceInspect: "核查账单可能发现供应商留下的线索。",
  confirmationRiskInvoicePayment: "无论如何都要处理这笔货款。",
  confirmationBenefitBalancedPolicy: "均衡作息提供稳定的夜间恢复。",
  confirmationRiskBalancedPolicy: "均衡作息不会强化夜间工作能力。",
  confirmationBenefitNightOwlPolicy: "夜猫子作息更适合晚间经营。",
  confirmationRiskNightOwlPolicy: "夜猫子作息会改变常规恢复节奏。",
} as const satisfies Readonly<Record<PocTextNameV1, string>>;

const pocTextNamesV1 = Object.freeze(Object.keys(pocTextIdsV1) as PocTextNameV1[]);

export const pocZhCnTextCatalogV1 = parseTextCatalogSetV1({
  defaultLocale: "zh-CN",
  catalogs: [
    {
      locale: "zh-CN",
      fallbackLocale: null,
      entries: pocTextNamesV1.map((name) => ({
        textId: pocTextIdsV1[name],
        text: pocZhCnTextByNameV1[name],
      })),
    },
  ],
}).catalogs[0]!;
