// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { collectManagedPaths } from "../../../../scripts/collect-import-closure.mjs";

const execFileAsync = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("../../../../", import.meta.url));
const outputUrl = new URL("../src/rule-source-digests.generated.ts", import.meta.url);
const outputPath = "game/stories/poc/src/rule-source-digests.generated.ts";

const roots = Object.freeze([
  Object.freeze({
    symbolId: "demand.preview",
    exportName: "pocDemandPreviewProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/demand.ts",
  }),
  Object.freeze({
    symbolId: "demand.resolve",
    exportName: "pocDemandResolveProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/demand.ts",
  }),
  Object.freeze({
    symbolId: "tavern.preview",
    exportName: "pocTavernPreviewProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/tavern.ts",
  }),
  Object.freeze({
    symbolId: "tavern.settle",
    exportName: "pocTavernSettleProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/tavern.ts",
  }),
  Object.freeze({
    symbolId: "checks.describe",
    exportName: "pocChecksDescribeProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/checks.ts",
  }),
  Object.freeze({
    symbolId: "checks.resolve",
    exportName: "pocChecksResolveProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/checks.ts",
  }),
  Object.freeze({
    symbolId: "endings.evaluate",
    exportName: "pocEndingsEvaluateProviderSourceDigestV1",
    entryPath: "game/stories/poc/src/gameplay/rule-provider-entries/endings.ts",
  }),
]);

async function sourceDigestV1(symbolId: string, entryPath: string): Promise<string> {
  const paths = await collectManagedPaths(repositoryRoot, [entryPath]);
  const records = await Promise.all(
    paths.map(async (path: string) => ({
      path,
      sha256: `sha256:${createHash("sha256")
        .update(await readFile(join(repositoryRoot, path)))
        .digest("hex")}`,
    })),
  );
  const canonicalProjection = JSON.stringify({ records, symbolId });
  const hash = createHash("sha256");
  hash.update("sillymaker:patch-provider:v1", "ascii");
  hash.update(Uint8Array.of(0));
  hash.update(canonicalProjection, "utf8");
  return `sha256:${hash.digest("hex")}`;
}

async function readCurrentOutputV1(): Promise<string | null> {
  try {
    return await readFile(outputUrl, "utf8");
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

const generatedExports = await Promise.all(
  roots.map(async ({ symbolId, exportName, entryPath }) => {
    const digest = await sourceDigestV1(symbolId, entryPath);
    return `export const ${exportName} =\n  ${JSON.stringify(digest)};`;
  }),
);
const nextOutput = `// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

${generatedExports.join("\n\n")}
`;
const currentOutput = await readCurrentOutputV1();

if (currentOutput !== nextOutput) {
  const { stdout } = await execFileAsync(
    "git",
    ["status", "--porcelain=v1", "--untracked-files=all", "--", outputPath],
    { cwd: repositoryRoot, encoding: "utf8" },
  );
  if (stdout.trim().length > 0) {
    throw new TypeError(`refusing to overwrite dirty or foreign generated output: ${outputPath}`);
  }
  await writeFile(outputUrl, nextOutput, "utf8");
}
