// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

export {
  deepFreezePocValueV1,
  parseSafeInteger,
  parseNonNegativeSafeInteger,
  parsePositiveSafeInteger,
  parseUint32,
  parseNonZeroUint32,
  parseDayIndex,
  parseAbsoluteDayIndex,
  parseMoodPoint,
  parseAttributeBonus,
  parseDieFace,
  parseMoney,
  parseQuantity,
} from "./contracts/values.js";

export type {
  Brand,
  DeepReadonly,
  SafeInteger,
  NonNegativeSafeInteger,
  PositiveSafeInteger,
  Uint32,
  NonZeroUint32,
  DayIndex,
  AbsoluteDayIndex,
  MoodPoint,
  AttributeBonus,
  DieFace,
  Money,
  Quantity,
  BeforeAfterV1,
  IntegerRangeV1,
  RatioV1,
} from "./contracts/values.js";

export {
  parseAssetId,
  parseCharacterId,
  parseRunId,
  parseTextId,
  actorIdsV1,
  attributeIdsV1,
  attributeRanksV1,
  relationshipStagesV1,
  calendarPhasesV1,
  serviceModesV1,
  openServiceModesV1,
  helperTiersV1,
  runStatusesV1,
  parseStoryId,
  parsePolicyId,
  parseActionId,
  parseEventId,
  parseCheckpointId,
  parseWeightedGroupId,
  parseSceneId,
  parseNodeId,
  parseChoiceId,
  parseFactId,
  parseQuestId,
  parseOutcomeId,
  parseIngredientId,
  parseItemId,
  parseRecipeId,
  parseFacilityId,
  parseAuraId,
  parseCustomerSegmentId,
  parseModifierSourceId,
  parseCheckId,
  parseCheckBandId,
  parseEndingId,
  parseReasonId,
  parseWorldStepId,
  parseFixtureId,
  parseStoryToken,
  parseFallbackToken,
  parseBatchId,
  parseAuraInstanceId,
  parseOpeningSessionId,
  parseLedgerEntryId,
  parseActorId,
  parseAttributeId,
  parseAttributeRank,
  parseRelationshipStage,
  parseCalendarPhase,
  parseServiceMode,
  parseOpenServiceMode,
  parseHelperTier,
  parseRunStatus,
} from "./contracts/ids.js";

export type {
  AssetId,
  CharacterId,
  RunId,
  TextId,
  StoryId,
  PolicyId,
  ActionId,
  EventId,
  CheckpointId,
  WeightedGroupId,
  SceneId,
  NodeId,
  ChoiceId,
  FactId,
  QuestId,
  OutcomeId,
  IngredientId,
  ItemId,
  RecipeId,
  FacilityId,
  AuraId,
  CustomerSegmentId,
  ModifierSourceId,
  CheckId,
  CheckBandId,
  EndingId,
  ReasonId,
  WorldStepId,
  FixtureId,
  StoryToken,
  FallbackToken,
  BatchId,
  AuraInstanceId,
  OpeningSessionId,
  LedgerEntryId,
  ActorId,
  AttributeId,
  AttributeRank,
  RelationshipStage,
  CalendarPhase,
  ServiceMode,
  OpenServiceMode,
  HelperTier,
  RunStatus,
} from "./contracts/ids.js";

export { pocDebugCommandKindsV1 } from "./contracts/types.js";

export type {
  StaminaStateV1,
  AttributeRanksV1,
  PlayerActorStateV1,
  HeroineActorStateV1,
  RelationshipStateV1,
  ActorsStateV1,
  InventorySourceRefV1,
  InventoryBatchV1,
  ItemStackV1,
  IngredientQuantityV1,
  ItemQuantityV1,
  BatchConsumptionV1,
  AuraTargetV1,
  AuraDurationUnitV1,
  AuraDurationV1,
  AuraDurationPolicyV1,
  AuraSourceRefV1,
  AuraInstanceV1,
  StatusStateV1,
  PlannedRecipeV1,
  TavernPlanV1,
  DemandRandomOffset,
  DemandSeedSegmentStateV1,
  DemandDayStateV1,
  AppliedModifierV1,
  MaterializedDemandSegmentV1,
  MaterializedDemandDayV1,
  FacilityStateV1,
  FacilityDecisionV1,
  FacilityDecisionRecordV1,
  HelperStateV1,
  DailyPreparationStateV1,
  LedgerCategoryV1,
  LedgerSubjectV1,
  LedgerEntryV1,
  LedgerEntryDraftV1,
  InventoryStateV1,
  OpeningOrderLineV1,
  OpeningLedgerV1,
  ClosureHistoryV1,
  ServiceHistoryEntryV1,
  OpeningActorInputsV1,
  OpeningBaselineV1,
  OpeningCheckpointV1,
  OpeningBlockingEventV1,
  OpeningSessionV1,
  WorldActionChoiceV1,
  WorldActionProgressV1,
  WorldActionSessionV1,
  ActiveWorkflowV1,
  TavernStateV1,
  FacilitiesStateV1,
  StoryValueV1,
  FactEntryV1,
  QuestStatusV1,
  QuestEntryV1,
  OutcomeEntryV1,
  NarrativeCursorV1,
  NarrativeCallFrameV1,
  CharacterSlotV1,
  NarrativeCharacterStateV1,
  NarrativeStageStateV1,
  NarrativeSourceV1,
  NarrativeRuntimeStateV1,
  StoryRuntimeStateV1,
  RunStateV1,
  CalendarStateV1,
  PocSimulationStateV1,
  PocGameStateV1,
  PurchaseLineV1,
  FacilityChoiceV1,
  PocGameCommandV1,
  ModifierSourceRefV1,
  ModifierV1,
  EffectIntentV1,
  PocEffectIntentV1,
  ProgressionEffectIntentV1,
  ChangeReasonV1,
  StaminaChangeComponentV1,
  PocGameplayFactV1,
  CommandReferenceV1,
  WorkflowBlockerV1,
  StoryRuleFaultCodeV1,
  CommandHandlerFaultCodeV1,
  EngineInvariantCodeV1,
  PocRejectionReasonV1,
  ConditionV1,
  AvailabilityGateV1,
  ConfirmationMetadataV1,
  StageCueV1,
  CheckRequestV1,
  NarrativeChoiceV1,
  NarrativeNodeV1,
  CheckBranchV1,
  NarrativeSceneV1,
  TextEntryV1,
  StoryCharacterDefinitionV1,
  ReasonDefinitionV1,
  CustomerSegmentDefinitionV1,
  ModifierSourceDefinitionV1,
  ActionOccupationDefinitionV1,
  ActionPresentationDefinitionV1,
  StoryActionDefinitionV1,
  IngredientDefinitionV1,
  ItemDefinitionV1,
  RecipeIngredientV1,
  SegmentPreferenceV1,
  RecipeDefinitionV1,
  ApByPhaseV1,
  LifePolicyDefinitionV1,
  FacilityDefinitionV1,
  FacilityOpportunityDefinitionV1,
  AuraDefinitionV1,
  WorldActionStepDefinitionV1,
  WorldActionOptionDefinitionV1,
  WorldActionDefinitionV1,
  EventTriggerV1,
  SchedulerContextV1,
  StoryEventDefinitionV1,
  CheckOutcomeBandV1,
  CheckDefinitionV1,
  EndingDefinitionV1,
  StoryValueDefinitionV1,
  FactDefinitionV1,
  QuestDefinitionV1,
  OutcomeDefinitionV1,
  StoryStateDefinitionsV1,
  StoryInitialStateV1,
  FixedActionCostKeyV1,
  ActionCostDefinitionV1,
  ServiceModeDefinitionV1,
  BaseDemandLineV1,
  LedgerReasonBindingsV1,
  EmergencyClosureDefinitionV1,
  ObligationForecastKindV1,
  ObligationRecommendationDefinitionV1,
  ObligationForecastPolicyV1,
  EndingPolicyV1,
  StoryBalanceV1,
  StoryContentV1,
  StorySourceIdentityV1,
  StoryManifestV1,
  PocStoryDataV1,
  PocSimulationManifestV1,
  PocSimulationContentV1,
  PocNarrativeProgramV1,
  PocSimulationDataV1,
  DemandSeedInputLineV1,
  DemandSeedInputV1,
  DemandSeedResultLineV1,
  DemandSeedResultV1,
  DemandProjectionInputV1,
  DemandPreviewLineV1,
  DemandPreviewV1,
  TavernPreviewInputV1,
  TavernOpeningCashCostV1,
  TavernOpeningCostsV1,
  TavernPreviewV1,
  TavernSettlementInputV1,
  SettlementDraftV1,
  CheckInputV1,
  CheckPreviewV1,
  CheckResultV1,
  ResolvedCheckV1,
  LevyResolutionV1,
  EndingInputV1,
  EndingSummaryV1,
  EndingResultV1,
  RunCompletionV1,
  PocRulesV1,
  StoryRuleSlotV1,
  PocSimulationProgramV1,
  CommandCostViewV1,
  ActionViewV1,
  AvailabilityExplanationV1,
  PreviewDeltaTargetV1,
  PreviewChangeV1,
  CommandConfirmationV1,
  CommandPreviewV1,
  NarrativeChoiceProjectionV1,
  NarrativeProjectionV1,
  DemandForecastV1,
  ObligationForecastBaseV1,
  ObligationForecastV1,
  RunStartControlProjectionV1,
  LifePolicyOptionProjectionV1,
  LifePolicySelectionProjectionV1,
  TavernOpeningControlProjectionV1,
  PocHudProjectionV1,
  PocInventoryBatchProjectionV1,
  PocInventoryProjectionV1,
  PocTavernProjectionV1,
  PocFacilitiesProjectionV1,
  PocLedgerProjectionV1,
  PocGameViewStatusV1,
  PocGameViewV1,
  PocGameQueriesV1,
  EngineFaultBaseV1,
  PocEngineFaultV1,
  PocDebugCommandV1,
  PocDebugReferenceV1,
  PocDebugCommandValidationErrorV1,
  PocGameBootstrapInputV1,
  PocGameSnapshotV1,
  PocCommandExecutionDiagnosticsV1,
  PocCommandExecutionAttemptV1,
  PocReplayableDebugExecutionResultV1,
  PocReplayableDebugExecutionAttemptV1,
  PocGameSimulationTypesV1,
} from "./contracts/types.js";

export {
  pocGameplayModuleKeysV1,
  pocGameplayModuleDependenciesV1,
  pocGameplayModuleDescriptorsV1,
  pocStateOwnerKeysV1,
  descriptorForPocModuleV1,
} from "./contracts/module-catalog.js";

export type { PocGameplayModuleKeyV1 } from "./contracts/module-catalog.js";

export {
  pocDebugCommandSchemaV1,
  pocDebugCommandValidationErrorSchemaV1,
  pocStoryStateDefinitionsSchemaV1,
  pocStoryInitialStateSchemaV1,
  pocStoryBalanceSchemaV1,
  pocSimulationManifestSchemaV1,
  pocSimulationContentSchemaV1,
  pocNarrativeProgramSchemaV1,
  pocSimulationDataSchemaV1,
} from "./contracts/schemas.js";

export { definePocGameplayModuleV1 } from "./contracts/define-poc-gameplay-module.js";

export {
  parsePocRunCompletionV1,
  pocRunCompletionSchemaV1,
  parsePocRunStateV1,
  pocRunStateSchemaV1,
  parsePocRunBootstrapInputV1,
  pocRunOwnerOperationSchemaV1,
  pocRunStatesEqualV1,
  pocRunOwnerProposalSchemaV1,
  parsePocRunDependencyPortsV1,
  pocRunInvariantV1,
} from "./modules/run/contract.js";

export type {
  PocRunOwnerOperationV1,
  PocRunOwnerProposalV1,
  PocRunReadPortV1,
  PocRunDependencyPortsV1,
} from "./modules/run/contract.js";

export {
  createInitialPocRunStateV1,
  createPocRunReadPortV1,
  pocRunOwnerV1,
  pocRunGameplayModuleV1,
} from "./modules/run/module.js";

export {
  pocCalendarStateSchemaV1,
  pocCalendarInvariantV1,
  pocCalendarOwnerOperationSchemaV1,
  pocCalendarDependencyPortsSchemaV1,
  pocCalendarStatesEqualV1,
  pocCalendarOwnerProposalSchemaV1,
} from "./modules/calendar/contract.js";

export type {
  PocCalendarPhasePointV1,
  PocCalendarDebugChangeReasonV1,
  PocCalendarOwnerOperationV1,
  PocCalendarOwnerProposalPayloadV1,
  PocCalendarGameplayFactV1,
  PocCalendarOwnerProposalV1,
  PocCalendarReadPortV1,
  PocCalendarDependencyPortsV1,
} from "./modules/calendar/contract.js";

export {
  createInitialPocCalendarStateV1,
  createPocCalendarReadPortV1,
  pocCalendarOwnerV1,
  pocCalendarGameplayModuleV1,
} from "./modules/calendar/module.js";

export {
  pocActorsStateSchemaV1,
  pocActorsInvariantV1,
  pocActorsOwnerOperationSchemaV1,
  parsePocActorsDependencyPortsV1,
  pocActorsDependencyPortsSchemaV1,
  pocActorsStatesEqualV1,
  pocActorsOwnerProposalSchemaV1,
} from "./modules/actors/contract.js";

export type {
  PocActorsOwnerOperationV1,
  PocActorsGameplayFactV1,
  PocActorsOwnerProposalPayloadV1,
  PocActorsOwnerProposalV1,
  PocActorsReadPortV1,
  PocActorsDependencyPortsV1,
} from "./modules/actors/contract.js";

export {
  createPocActorsReadPortV1,
  pocActorsOwnerV1,
  createPocActorsGameplayModuleV1,
} from "./modules/actors/module.js";

export type { PocActorsGameplayModuleV1 } from "./modules/actors/module.js";

export {
  parsePocAuraTargetV1,
  parsePocAuraDurationV1,
  parsePocAuraInstanceV1,
  parsePocChangeReasonV1,
  pocStatusStateSchemaV1,
  pocStatusDependencyPortsSchemaV1,
  pocStatusOwnerOperationSchemaV1,
  pocStatusStatesEqualV1,
  pocStatusOwnerProposalSchemaV1,
  pocStatusInvariantV1,
} from "./modules/status/contract.js";

export type {
  PocStatusAuraDefinitionPortV1,
  PocStatusDependencyPortsV1,
  PocStatusOwnerOperationV1,
  PocStatusGameplayFactV1,
  PocStatusOwnerProposalPayloadV1,
  PocStatusOwnerProposalV1,
  PocStatusReadPortV1,
} from "./modules/status/contract.js";

export {
  advancePocAuraCountdownsV1,
  createPocStatusReadPortV1,
  pocStatusOwnerV1,
  createPocStatusGameplayModuleV1,
} from "./modules/status/module.js";

export type {
  PocStatusOwnerCapabilityV1,
  PocAuraCountdownInputV1,
  PocAuraCountdownResultV1,
  PocStatusGameplayModuleV1,
} from "./modules/status/module.js";

export {
  parsePocInventoryChangeReasonV1,
  parsePocInventorySourceRefV1,
  parsePocInventoryBatchV1,
  parsePocInventoryItemStackV1,
  parsePocInventoryLedgerSubjectV1,
  parsePocInventoryLedgerEntryV1,
  parsePocInventoryLedgerEntryDraftV1,
  parsePocInventoryStateV1,
  pocInventoryStateSchemaV1,
  pocInventoryOwnerOperationSchemaV1,
  comparePocInventoryBatchIdsV1,
  pocInventoryDependencyPortsSchemaV1,
  pocInventoryOwnerProposalSchemaV1,
  comparePocInventoryLedgerEntryIdsV1,
  comparePocInventoryFifoBatchesV1,
  sortPocInventoryBatchesV1,
  sortPocInventoryItemStacksV1,
  pocInventoryStatesEqualV1,
  pocInventoryInvariantV1,
  assertValidInitialPocInventoryStateV1,
} from "./modules/inventory/contract.js";

export type {
  PocInventoryIngredientPortV1,
  PocInventoryShelfLifeExtensionV1,
  PocInventoryLedgerAppendContextV1,
  PocInventoryOwnerOperationV1,
  PocInventoryDependencyPortsV1,
  PocInventoryGameplayFactV1,
  PocInventoryOwnerProposalPayloadV1,
  PocInventoryOwnerProposalV1,
  PocInventoryReadPortV1,
} from "./modules/inventory/contract.js";

export {
  createPocInventoryReadPortV1,
  pocInventoryOwnerV1,
  createPocInventoryGameplayModuleV1,
} from "./modules/inventory/module.js";

export type { PocInventoryGameplayModuleV1 } from "./modules/inventory/module.js";

export {
  comparePocFacilityIdsV1,
  comparePocFacilityOpportunityIdsV1,
  parsePocFacilityDecisionV1,
  parsePocFacilityChoiceV1,
  parsePocFacilityStateV1,
  parsePocFacilityDecisionRecordV1,
  parsePocFacilitiesStateV1,
  pocFacilitiesStateSchemaV1,
  sortPocFacilityStatesV1,
  sortPocFacilityDecisionRecordsV1,
  pocFacilitiesInvariantV1,
  pocFacilitiesOwnerOperationSchemaV1,
  parsePocFacilitiesDependencyPortsV1,
  pocFacilitiesDependencyPortsSchemaV1,
  pocFacilitiesStatesEqualV1,
  assertValidInitialPocFacilitiesStateV1,
  pocFacilitiesOwnerProposalSchemaV1,
} from "./modules/facilities/contract.js";

export type {
  PocFacilitiesOpportunityPortV1,
  PocFacilitiesOwnerOperationV1,
  PocFacilitiesDependencyPortsV1,
  PocFacilitiesGameplayFactV1,
  PocFacilitiesOwnerProposalPayloadV1,
  PocFacilitiesOwnerProposalV1,
  PocFacilitiesReadPortV1,
} from "./modules/facilities/contract.js";

export {
  createPocFacilitiesReadPortV1,
  pocFacilitiesOwnerV1,
  createInitialPocFacilitiesStateV1,
  pocFacilitiesGameplayModuleV1,
} from "./modules/facilities/module.js";

export {
  parsePocTavernChangeReasonV1,
  parsePocTavernHelperStateV1,
  parsePocTavernPlanV1,
  parsePocTavernDemandDayV1,
  parsePocTavernMaterializedDemandDayV1,
  parsePocTavernOpeningLedgerV1,
  parsePocTavernClosureHistoryV1,
  parsePocTavernServiceHistoryEntryV1,
  parsePocTavernStateV1,
  pocTavernStateSchemaV1,
  pocTavernOwnerOperationSchemaV1,
  pocTavernDependencyPortsSchemaV1,
  pocTavernStatesEqualV1,
  pocTavernInvariantV1,
  assertValidPocTavernStateV1,
  assertValidInitialPocTavernStateV1,
  sortPocTavernRecipeIdsV1,
  pocTavernOwnerProposalSchemaV1,
} from "./modules/tavern/contract.js";

export type {
  PocTavernOwnerOperationV1,
  PocTavernPlanRecipePortV1,
  PocTavernPlanDependenciesV1,
  PocTavernPreparationDependenciesV1,
  PocTavernDependencyPortsV1,
  PocTavernReadPortV1,
  PocTavernGameplayFactV1,
  PocTavernOwnerProposalPayloadV1,
  PocTavernOwnerProposalV1,
} from "./modules/tavern/contract.js";

export {
  createPocTavernReadPortV1,
  pocTavernOwnerV1,
  createPocTavernGameplayModuleV1,
} from "./modules/tavern/module.js";

export type { PocTavernGameplayModuleV1 } from "./modules/tavern/module.js";
