// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:70090547ca76ca5d8efb4e705afef23435b043fc8b27701fbfd8140b09448ca8";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:bd7cfd499361081bf3ba8404375fb7d81fe9b4ed68eba3e87df9a77293d58cb0";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:0b1180c9c23f2fc342c275f2f97e8dacef411df32b8ae0c54d5ba1bc19b2f68c";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:dfa96f8340020d502048308c8523f3a408ba42655cc7ec4f0b0a06eea7f5c67a";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:e5e74397eabd63ce92d24dd303ba38eba54474a46466f20b8325fb3a363b7268";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:34d577f0df9f4952f20efacaccce3b243053e1104ce28e8adce0e3a6434dc297";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:df2f3ff3b6ce600fc537a1e159a34912f94ab9d3f736f3992bae3df6775009b9";
