// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:76e889de7aab4b3a12561c083f8a8c4c424f81b5d000f6a74bf7a4d4e3829e13";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:54a510f573009251a5c2ad5c58f7cc4fa1a65070de4748d4b302acd8fbbff80d";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:e5e2ee7f0a655ad74df5c0a373dd324d6d808459129372cad153c219eba777e1";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:e779c54c4cf8fc197be71b055d427f8c7d31ba41b0b5fa7903fbd6c9e36e8db7";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:43cba9112e42d2d3cdebe1977fb562edee9cb6f25ca3c58c1e787702e506b636";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:1236070084b1baf243dd19f9021487c9082b48b3811569c68c1555fb0e99c2c8";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:55850759372a7939cb7f29b4cacf304a1b15f81824ce2f18d47b6934c1eb7d6b";
