// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-rule-source-digests.mts. Do not edit manually.

export const pocDemandPreviewProviderSourceDigestV1 =
  "sha256:de7e34b8e2249c53677e1da3da2cf86bab593f04d43f7e158ba30d9b834a20d1";

export const pocDemandResolveProviderSourceDigestV1 =
  "sha256:16fc5cec20e3313222b8c782588a0a9e55f0b930175c3ba342f436c9037bc77d";

export const pocTavernPreviewProviderSourceDigestV1 =
  "sha256:3bc990dae359b24971faea2f62f10b979c7c1acdc5efb3f0990baa2628b14bdb";

export const pocTavernSettleProviderSourceDigestV1 =
  "sha256:9246427c9a52bfe83d9b73024e688506859e1d6cdc54a0940a4c34a682292238";

export const pocChecksDescribeProviderSourceDigestV1 =
  "sha256:d021515c6b1858010806c54e54f4a2235248585f38654f1b679b3a5008b76d40";

export const pocChecksResolveProviderSourceDigestV1 =
  "sha256:a300f1071715335987fe8c21560a8122ac7235cd948ecc84278bdf4e9fc15798";

export const pocEndingsEvaluateProviderSourceDigestV1 =
  "sha256:862b644937d4003d15c7a2a389805ca64b999a24179e239a2aa215c3934d5c34";
