// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-source-digests.mts. Do not edit manually.

export const e2eChoiceDeltaProviderSourceDigestV1 =
  "sha256:65e50931d4f3821fe634c90c92d7cee6a817a2b154023a1b5e9b1d82eb5a16b6";

export const e2eChoiceDeltaHotfixSourceDigestV1 =
  "sha256:ff70543ba5a22dfa46d5680bbcc22890266e0ea6fe46d2fb0b16e0f8198595ce";
