// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import {
  assertCleanGeneratedOutputPathV1,
  assertClosedExecutableSourceRootV1,
} from "./executable-source-root.mts";

const execFileAsync = promisify(execFile);

function sha256V1(bytes: Uint8Array | string): string {
  return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

function digestExecutableSourceV1(domain: string, path: string, bytes: Uint8Array): string {
  const sourceDigest = sha256V1(bytes);
  const canonicalRecords = `{"records":[{"path":${JSON.stringify(path)},"sha256":${JSON.stringify(sourceDigest)}}]}`;
  const hash = createHash("sha256");
  hash.update(domain, "ascii");
  hash.update(Uint8Array.of(0));
  hash.update(canonicalRecords, "utf8");
  return `sha256:${hash.digest("hex")}`;
}

const roots = Object.freeze([
  Object.freeze({
    exportName: "e2eChoiceDeltaProviderSourceDigestV1",
    domain: "sillymaker:patch-provider:v1" as const,
    path: "game/stories/e2e/src/simulation/choice-delta-provider.ts",
    url: new URL("../src/simulation/choice-delta-provider.ts", import.meta.url),
  }),
  Object.freeze({
    exportName: "e2eChoiceDeltaHotfixSourceDigestV1",
    domain: "sillymaker:hotfix:v1" as const,
    path: "game/stories/e2e/src/simulation/choice-delta-hotfix.ts",
    url: new URL("../src/simulation/choice-delta-hotfix.ts", import.meta.url),
  }),
]);

const exports: string[] = [];
for (const root of roots) {
  const bytes = new Uint8Array(await readFile(root.url));
  assertClosedExecutableSourceRootV1(root.path, bytes);
  const digest = digestExecutableSourceV1(root.domain, root.path, bytes);
  exports.push(`export const ${root.exportName} =\n  ${JSON.stringify(digest)};`);
}

const output = `// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Generated by scripts/update-source-digests.mts. Do not edit manually.

${exports.join("\n\n")}
`;
const outputUrl = new URL("../src/simulation/source-digests.generated.ts", import.meta.url);
const outputPath = "game/stories/e2e/src/simulation/source-digests.generated.ts";
let currentOutput: string | null;
try {
  currentOutput = await readFile(outputUrl, "utf8");
} catch (error) {
  if (
    typeof error !== "object" ||
    error === null ||
    !("code" in error) ||
    error.code !== "ENOENT"
  ) {
    throw error;
  }
  currentOutput = null;
}

if (currentOutput !== output) {
  const repositoryRoot = fileURLToPath(new URL("../../../../", import.meta.url));
  const { stdout: outputStatus } = await execFileAsync(
    "git",
    ["status", "--porcelain=v1", "--untracked-files=all", "--", outputPath],
    { cwd: repositoryRoot, encoding: "utf8" },
  );
  assertCleanGeneratedOutputPathV1(outputPath, outputStatus);
  await writeFile(outputUrl, output, "utf8");
}
